### ISSUE TITLE
convertor.php error

### ISSUE THREAD

**Issue by mohcen** [mihailShumilov/mysql2postgresql#13]
Hi,
I've issue with running the convert command. it errors like "Can't  parse XML data"

**Comment by mihailShumilov** [comment]
Can You provide XML that You want to convert?

**Comment by mohcen** [comment]
Thanks dude for the fast reply. here it´s

**Comment by mohcen** [comment]
Thanks dude for the fast reply. here it´s

**Comment by mohcen** [comment]
Thanks dude for the fast reply. here it´s

**Comment by mohcen** [comment]
Thanks dude for the fast reply. here it´s

**Comment by mohcen** [comment]
Thanks dude for the fast reply. here it´s

**Comment by mohcen** [comment]
Thanks dude for the fast reply. here it´s

**Comment by mohcen** [comment]
Thanks dude for the fast reply. here it´s

**Comment by mohcen** [comment]
Thanks dude for the fast reply. here it´s

**Comment by mohcen** [comment]
Thanks dude for the fast reply. here it´s

**Comment by mohcen** [comment]
Thanks dude for the fast reply. here it´s

**Comment by mohcen** [comment]
Thanks dude for the fast reply. here it´s

**Comment by dukhanin** [comment]
Got the same error on parsing "Can't parse XML data"

Suppose it was caused by ASCII chars in utf-8 dump, so i just added code cutting ascii chars and it was fixed for me:

`$data = preg_replace('/[\x00-\x1F\x80-\xFF]/', '', $data);
xml_parse( $xml, $data, feof( $this->iFh ) ) or die( "Can't parse XML data" );`

**Comment by mihailShumilov** [comment]
Can You attach xml file? I will check also?

**Comment by tishakariya** [comment]
Hi,
Is there any solution for this error, I am getting the same error
Error: Invalid character
Errored line: 22
Errored column: 16
Errored index: 1302
**Can't parse XML data**

**Comment by mihailShumilov** [comment]
Can You attach xml file?
