### ISSUE TITLE
Quoting all table and column names

### ISSUE THREAD

**Issue by cmarmo** [mihailShumilov/mysql2postgresql#2]
Hello Mihail,
first of all thanks for your code, you saved my life! :)
I just want to report a problem with quotes in the output sql file.
Column names are quoted when the table is created but table names are not.
In index creation commands table and columns are not quoted (see attached output example)

```
DROP TABLE IF EXISTS regionCodes;

CREATE TABLE regionCodes (
	"idregion" serial NOT NULL ,
	"regionName" varchar(45) NOT NULL ,
	"regionCode" varchar(2) NOT NULL ,
	PRIMARY KEY ("idregion")

);
CREATE UNIQUE INDEX "regionCodes_regionName_UNIQUE" ON regionCodes (regionName);
CREATE UNIQUE INDEX "regionCodes_regionCode_UNIQUE" ON regionCodes (regionCode);
```
This could be produced errors in importing.
If you have time to take a look...

Thanks again for your code!
Chiara

**Comment by mihailShumilov** [comment]
Hi!

Thanks for feedback, it's really very important for me
I made some changes, now it will works as expected.
Please check it and leave a comment

**Comment by cmarmo** [comment]
Thanks for your quick answer!
You are almost there... :)
The ```INSERT into``` too need quotes 
```
INSERT INTO imformats ("idimformats","format") VALUES 
('1','FITS2D'),
('2','FITS3D'),
('3','JPEG'),
('4','BMP'),
('5','AVI');
```

**Comment by mihailShumilov** [comment]
Oh, thanks for reply
I fixed it right now

**Comment by cmarmo** [comment]
Hello,
still me... I restarted from scratch with your last version and I discovered the same problem of case sensitivity in this line
```
SELECT setval('regionCodes_idregion_seq', 22);
```
and I fixed it by hand by
```
SELECT setval('"regionCodes_idregion_seq"', 22);
```
Is that the good fix?

(sorry for the spare parts bug report)
Chiara

**Comment by mihailShumilov** [comment]
Khm
Your fix looks not so good
I will research this problem

**Comment by mihailShumilov** [comment]
After reading documentation at http://www.postgresql.org/docs/9.4/static/functions-sequence.html
I agree with Your patch
I updated code with Your suggestions

**Comment by cmarmo** [comment]
It works!
That's wonderful! :)
Thanks a lot!
Chiara
