### ISSUE TITLE
Call to undefined function pg_escape_string()

### ISSUE THREAD

**Issue by b1tdreamer** [mihailShumilov/mysql2postgresql#20]
I receive this error when I tried to execute the php:

PHP Fatal error:  Call to undefined function pg_escape_string() in /root/mysql2postgresql/Convertor.class.php on line 202

I searched and I only found this line about pg_escape_string()

$item = pg_escape_string( $item );

Do you have any ideas of the problem?
Thanks

**Comment by Extrapolator214** [comment]
You need to install postgres extension:
`sudo apt-get install php5-pgsql`

**Comment by mihailShumilov** [comment]
:+1:

**Comment by LennyLip** [comment]
please, add requirements info to README
