### ISSUE TITLE
missing function and undefined index

### ISSUE THREAD

**Issue by johnbianchi** [mihailShumilov/mysql2postgresql#7]
Running on rhel6 x64 ... are there any other php packages I need to get "pg_escape_string()" function?

$ php convertor.php -i confluence.xml -o confluence.pgsql
PHP Notice:  Undefined index: b in /mnt/data/backup/mysql2postgresql-master/convertor.php on line 15
PHP Notice:  Undefined index: batch-count in /mnt/data/backup/mysql2postgresql-master/convertor.php on line 15

PHP Fatal error:  Call to undefined function pg_escape_string() in /mnt/data/backup/mysql2postgresql-master/Convertor.class.php on line 199

**Comment by mihailShumilov** [comment]
Hi!

Thanks for Your response

Issue with PHP Notice was fixed

About PHP Fatal error - You must have installed locally php postgresql extenstion
